# Generated by Django 5.2.3 on 2025-08-19 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="networknode",
            name="employees",
            field=models.ManyToManyField(
                related_name="network_nodes", to=settings.AUTH_USER_MODEL, verbose_name="Сотрудники"
            ),
        ),
        migrations.AddField(
            model_name="networknode",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Единственный поставщик данного звена",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="network.networknode",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="network.networknode",
                verbose_name="Владелец",
            ),
        ),
    ]
